Version 2! Now with more working!
- Fix dependency checks
- Add keystore integrity checks to init
- Add auto-branch creation to key generation
- Implement key lookups by email
- Fallback to local cache when possible if remote key retrieval fails
- Typo fixes!
- Ability to define a keystore and hae it remembered
- much, much more

diff --git a/secnotes b/secnotes
--- a/secnotes
+++ b/secnotes
@@ -1,12 +1,13 @@
 #!/bin/bash
 MASTER_KEY='6D806CDF'
-SETTINGS=~/.config/secnotes
+SETTINGS=~/.config/secnotes/config
+KEYSTORE_LOCATION="${SETTINGS%/*}/keystore"
 # Expected variables from settings:
 # KEY_ID - the key ID to use for this user
 # EMAIL - email of the generated key. Used for all encryption/decryption
-# REPO - git repository of email/fingerprint pairs to trust
+# KEYSTORE - git repository of email/fingerprint pairs to trust
+KEY_ID=''
 EMAIL=''
-REPO=''
 if [[ -f $SETTINGS ]]; then
 	while read -r line; do declare $line; done < $SETTINGS
 fi
@@ -16,9 +17,9 @@ g() { tput setaf 2; tput bold; }
 y() { tput setaf 3; tput bold; }
 b() { tput setaf 4; tput bold; }
 c() { tput sgr0; }
-error() { echo "$(r)Error$(c): $*"; }
-warning() { echo "$(y)Warning$(c): $*"; }
-success() { echo "$(g)Success$(c): $*"; }
+error() { echo "$(r)Error$(c): $*" >&2; }
+warning() { echo "$(y)Warning$(c): $*" >&2; }
+success() { echo "$(g)Success$(c): $*" >&2; }
 
 # Detect and install packages if necessary
 init() {
@@ -42,22 +43,29 @@ init() {
 		fi
 	fi
 
-	if ! which gpg2 &>/dev/null || ! which tput &>/dev/null; then
-		error "A problem has occurred while trying to detect gpg2; please ensure it is available in your current environment"
+	if ! which gpg2 &>/dev/null || ! which tput &>/dev/null || which haveged &>/dev/null; then
+		error "A problem has occurred while trying to detect gpg2 and dependencies; please ensure it is available in your current environment"
 	fi
 
 	# Trust master key
-	if ! gpg2 --list-keys | grep -q $MASTER_KEY; then
-		warning "Master key not found. Importing..."
+	if ! gpg2 --list-keys 2>&1 | grep -q $MASTER_KEY; then
+		warning "Master key not found. Downloading..."
 		GPG_OUT=$(gpg2 --recv-key $MASTER_KEY 2>&1)
 		rc=$?
 		[[ $rc -ne 0 ]] && error "Failed retrieving master key!" && echo "$GPG_OUT" && exit $rc
 	fi
 
-	if ! gpg2 --list-keys --list-options show-uid-validity | grep -a1 $MASTER_KEY | grep -q 'ultimate'; then
-		warning "Master key not ultimately trust. Fixing..."
-		OWNERTRUST=$(gpg2 --list-keys --with-fingerprint --with-colons | grep -A1 'ops@c9.io' | tail -n1 | tr -s : : | cut -d: -f2):6:
-		GPG_OUT=$(gpg2 --import-ownertrust <<<"$OWNERTRUST")
+	if ! gpg2 --list-keys --list-options show-uid-validity 2>&1 | grep -a1 $MASTER_KEY | grep -q 'ultimate'; then
+		warning "Master key not ultimately trusted. Fixing..."
+		OWNERTRUST=$(gpg2 --list-keys --with-fingerprint --with-colons 2>&1 | grep -A1 'ops@c9.io' | tail -n1 | tr -s : : | cut -d: -f2):6:
+		GPG_OUT=$(gpg2 --import-ownertrust <<<"$OWNERTRUST" 2>&1)
+	fi
+
+	if [[ -d $KEYSTORE_LOCATION ]]; then
+		git -C "$KEYSTORE_LOCATION" git fetch --all &>/dev/null
+		git -C "$KEYSTORE_LOCATION" git reset --hard &>/dev/null
+		git -C "$KEYSTORE_LOCATION" git checkout master &>/dev/null
+		git -C "$KEYSTORE_LOCATION" git reset --hard origin/master &>/dev/null
 	fi
 }
 
@@ -69,12 +77,11 @@ grep_keyid() {
 	grep pub | sed -E 's|.*/([a-zA-Z0-9]+).*$|\1|'
 }
 
-# Check if key is at $KEY_LOCATION return 0 if it exists
 check_for_secret_key() {
 	[[ -z $EMAIL ]] && return 1
 	[[ -z $KEY_ID ]] && return 1
 
-	SECRET_KEYS=$(gpg2 --list-secret-keys)
+	SECRET_KEYS=$(gpg2 --list-secret-keys 2>&1)
 	GPG_EMAIL=$(grep -A1 "$KEY_ID" <<<"$SECRET_KEYS" | grep_email)
 	[[ $GPG_EMAIL == "$EMAIL" ]] && return 0
 	return 1
@@ -82,7 +89,8 @@ check_for_secret_key() {
 
 # Use GPG to generate a key and store the key variables for later use
 generate_key() {
-	# TODO: May not work in docker containers. Need to test
+	[[ ! -d $KEYSTORE_LOCATION ]] && error 'Please specify a keystore repository before generating your key' && exit 1
+	# TODO: May not work in docker containers. Need to test; or ignore because this should be on local host only
 	ps aux | grep haveged|grep -qv grep || sudo haveged
 	if check_for_secret_key; then
 		echo "A key has already been generated. Are you sure you want to continue? [y/N]"
@@ -100,9 +108,24 @@ generate_key() {
 	EMAIL=$(grep_email <<<"$NEW_KEY")
 	[[ -z $KEY_ID ]] && error 'Failed to generate key!' && return 1
 	[[ -z $EMAIL ]] && error 'Failed to generate key!' && return 1
-	GPG_OUT=$(gpg --send-key "$KEY_ID" 2>&1)
+	GPG_OUT=$(gpg2 --send-key "$KEY_ID" 2>&1)
 	rc=$?
-	[[ $rc -ne 0 ]] && error 'Failed to upload key to server!' && return $rc
+	# TODO: Cleanup after failure to upload?
+	[[ $rc -ne 0 ]] && error 'Failed to upload key to server!' && echo "$GPG_OUT" && return $rc
+
+	# Attempt to silently clear branches of the existing name before doing set -e
+	git -C "$KEYSTORE_LOCATION" branch -D "$EMAIL"
+	set -e
+	trap 'error Failed to upload new key to keystore' SIGQUIT SIGINT SIGTERM EXIT
+	# Save key to repo and push in a branch
+	echo "$KEY_ID" > "$KEYSTORE_LOCATION/$EMAIL"
+	git -C "$KEYSTORE_LOCATION" checkout -b "$EMAIL"
+	git -C "$KEYSTORE_LOCATION" add "$EMAIL"
+	git -C "$KEYSTORE_LOCATION" commit -m "New key for $EMAIL"
+	git -C "$KEYSTORE_LOCATION" push --set-upstream origin HEAD
+	git -C "$KEYSTORE_LOCATION" checkout master
+	trap - SIGQUIT SIGINT SIGTERM EXIT
+	set +e
 
 	# Save settings for future use
 	echo "KEY_ID=$KEY_ID" > "$SETTINGS"
@@ -111,31 +134,42 @@ generate_key() {
 	return 0
 }
 
-# TODO: Implement this.
 get_keyid_from_email() {
-	# Probably just check in git database; otherwise fail. Just use public key servers for lookup/download of keys
-	# it's hard to revoke keys on the public servers unless you have the revocation certificate,
-	# and even then searches can only return the first result for the email; making it possible to get the wrong key
-	# (MAYBE) Fall back to keyserver lookup
+	local TARGET=$1
+	local fullname="$KEYSTORE_LOCATION/$TARGET"
+	local shortname=$(find "$KEYSTORE_LOCATION" -maxdepth 1 -iname "$TARGET*")
 
-	# return key ID
-	echo DC734EC8
-	return 0
+	# keystore lookup
+	for file in $fullname $shortname; do
+		[[ -f $file ]] && cat "$file" && return 0
+	done
+
+	# TODO: Implement remote keystore lookup here after falling through local checks
+	error 'Failed to find key locally. Remote lookups coming soon'
+	return 1
 }
 
-# TODO: Check if key is in the repo for encrypting. Add a --force option otherwise?
+# Attempt to recieve the specified KEYID; fallback to local cache if it fails
 get_public_key() {
 	local GPG_OUT
 	local rc=0
-	keyid="$1"
-	# check if key is already in keyring
-	if gpg2 --list-keys | grep -q "$keyid"; then
-		GPG_OUT=$(gpg2 --recv-key "$keyid")
-		rc=$?
-		[[ $rc -ne 0 ]] && error "Unable to retrieve key" && echo "$GPG_OUT"
-		return $rc
+	local KEYID="$1"
+
+	GPG_OUT=$(gpg2 --recv-key "$KEYID" 2>&1)
+	rc=$?
+
+	if gpg --list-keys | grep -q $KEYID; then
+		if [[ $rc -eq 0 ]]; then
+			return 0
+		else
+			warning 'Failed to update key. Falling back to local cache.'
+			rc=0
+		fi
+	else
+		error 'Failed to retrieve key'
 	fi
-	return 0
+	echo $GPG_OUT
+	return $rc
 }
 
 encrypt_message() {
@@ -151,16 +185,15 @@ encrypt_message() {
 
 	[[ -z $RECIPIENT ]] && error "No recipient specified! This shouldn't happen." && exit 1
 
-	if [[ $RECIPIENT =~ @ ]]; then
-		KEYID=$(get_keyid_from_email $RECIPIENT)
-	else
-		KEYID=$RECIPIENT
-	fi
+	# Set $KEYID assuming $RECIPIENT is an email. Fallback to using it as the ID itself
+	KEYID=$(get_keyid_from_email $RECIPIENT)
+	[[ -z $KEYID ]] && KEYID=$RECIPIENT
 	get_public_key "$KEYID"
+	[[ $? -ne 0 ]] && exit 1
 
 	if [[ $FILE == - ]]; then
 		# File is stdin
-		GPG_OUT=$(gpg2 -r $RECIPIENT --armor --encrypr 3>&1 1>&2 2>&3)
+		GPG_OUT=$(gpg2 -r $RECIPIENT --armor --encrypt 3>&1 1>&2 2>&3)
 		rc=$?
 	elif [[ -n $FILE ]]; then
 		# File is a file
@@ -181,15 +214,13 @@ encrypt_message() {
 
 	3>&-
 	if [[ $rc -ne 0 ]]; then
-		error "Failed to decrypt message!"
+		error "Failed to encrypt message!"
 		echo "$GPG_OUT"
 	fi
 	return $rc
 
 }
 
-# TODO: What do we want to do with the gpg decryption output? who signed it, etc
-# Currently outputting it on errors, supressing on success. Should we verify the ID is in the git repo?
 decrypt_message() {
 	local GPG_OUT
 	local INPUT
@@ -233,8 +264,33 @@ decrypt_message() {
 
 # set a git repo to use for validating fingerprints
 set_keystore() {
-	REPO=$1
+	[[ -z $KEYSTORE ]] && error "No keystore specified! This shouldn't happen" && exit 1
+	if [[ -d $KEYSTORE_LOCATION ]]; then
+		error "A keystore has already been specified. Are you sure you wish to overwrite it? [y/N]"
+		read -r response
+		case $response in
+			y|Y)echo '';;
+			*)exit 1;;
+		esac
+		rm -rf "$KEYSTORE_LOCATION"
+	fi
 
+	handler() {
+		error 'Failed to clone keystore!'
+		exit 1
+	}
+
+	set -e
+	trap handler SIGTERM SIGINT SIGQUIT EXIT
+	# Github shortname handling
+	if ! [[ $KEYSTORE =~ (@|:) ]]; then
+		KEYSTORE="git@github.com:$KEYSTORE"
+	fi
+	git clone "$KEYSTORE" "$KEYSTORE_LOCATION" &>/dev/null
+
+	set +e
+	trap - SIGTERM SIGINT SIGQUIT EXIT
+	return 0
 }
 
 usage() {
@@ -253,7 +309,7 @@ usage() {
 	            You must specify the email of the person you intend to send this to
 	 -f file    Specify a $(b)F$(c)ile. Specifying '-' will use stdin
 	 -g         $(b)G$(c)enerate a key pair; This should only be needed once
-	 -s repo    $(b)S$(c)et a git repository to use for verifying key IDs
+	 -s repo    $(b)S$(c)et a git repo as the keystore for verifying key IDs
 	EOF
 }
 
