Move trust_master_key to its own function

diff --git a/secnotes b/secnotes
--- a/secnotes
+++ b/secnotes
@@ -92,6 +92,26 @@ install_package() {
 	return 1
 }
 
+trust_master_key() {
+	local OWNERTRUST
+	local GPG_OUT
+	local rc
+
+	if ! gpg2 --list-keys 2>&1 | grep -q $MASTER_KEY; then
+		warning "Master key not found. Downloading..."
+		GPG_OUT=$(gpg2 --recv-key $MASTER_KEY 2>&1)
+		rc=$?
+		[[ $rc -ne 0 ]] && error "Failed retrieving master key!" && echo "$GPG_OUT" && exit $rc
+	fi
+
+	if ! gpg2 --list-keys --list-options show-uid-validity 2>&1 | grep -a1 $MASTER_KEY | grep -q 'ultimate'; then
+		warning "Master key not ultimately trusted. Fixing..."
+		OWNERTRUST=$(gpg2 --list-keys --with-fingerprint --with-colons 2>&1 | grep -B1 'ops@c9.io' | head -n1 | tr -s : : | cut -d: -f2):6:
+		GPG_OUT=$(gpg2 --import-ownertrust <<<"$OWNERTRUST" 2>&1)
+		[[ $? -ne 0 ]] && error "Failed to trust master key!" && echo "$GPG_OUT" && exit 1
+	fi
+}
+
 # Detect and install packages if necessary
 init() {
 	local GPG_OUT
@@ -111,20 +131,7 @@ init() {
 	install_package clipit clipit clipit ''
 	set +e
 
-	# Trust master key
-	if ! gpg2 --list-keys 2>&1 | grep -q $MASTER_KEY; then
-		warning "Master key not found. Downloading..."
-		GPG_OUT=$(gpg2 --recv-key $MASTER_KEY 2>&1)
-		rc=$?
-		[[ $rc -ne 0 ]] && error "Failed retrieving master key!" && echo "$GPG_OUT" && exit $rc
-	fi
-
-	if ! gpg2 --list-keys --list-options show-uid-validity 2>&1 | grep -a1 $MASTER_KEY | grep -q 'ultimate'; then
-		warning "Master key not ultimately trusted. Fixing..."
-		OWNERTRUST=$(gpg2 --list-keys --with-fingerprint --with-colons 2>&1 | grep -B1 'ops@c9.io' | head -n1 | tr -s : : | cut -d: -f2):6:
-		GPG_OUT=$(gpg2 --import-ownertrust <<<"$OWNERTRUST" 2>&1)
-		[[ $? -ne 0 ]] && error "Failed to trust master key!" && echo "$GPG_OUT" && exit 1
-	fi
+	trust_master_key
 }
 
 update_keystore() {
